apiVersion: v1
kind: Service
metadata:
  name: python-load
spec:
  selector:
    app: python-flask
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
      protocol: TCP
